Controllers
MalishkaMyu/EmployeesDepartment pull request #10
Opened 2023-02-13 10:27 UTC by MalishkaMyu

2023-03-01 07:52 UTC, AlecKotovichSAM requested changes

2023-03-01 07:52 UTC, AlecKotovichSAM commented on build.gradle
> +	// https://mvnrepository.com/artifact/com.querydsl/querydsl-core
this comment is not needed, because dep is self explanatory

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/controllers/rest/EmployeeController.java
> +    @Autowired
Add empty line

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/controllers/rest/UserController.java
> +    @Autowired
Add empty line

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/controllers/rest/UserController.java
> +        return createdUser != null
Add empty line

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/controllers/rest/UserController.java
> +        return user != null
Add empty line

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/exception/GlobalExceptionHandler.java
> +        if ((employeesdepGlobalException.getObjectClass() != null)) {
двойные скобки зачем?

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/converters/UserDTOToEntityConverter.java
> +        if (source.getPasswordHash() != null && !source.getPasswordHash().isBlank()) {
This can be replaced with StringUtils.isBlank...

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/services/impl/EmployeeServiceImpl.java
>          // check whether employee with the name already exists
Add empty line

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/services/impl/EmployeeServiceImpl.java
> +                roleToSave = roleRepository.find(roleDTO.getId()).orElse(null);
put it into { }

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/services/impl/EmployeeServiceImpl.java
>              // employee is not still exists
employee is not still exists -> employee does not still exist

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/services/impl/EmployeeServiceImpl.java
> +                roleToSave = roleRepository.find(roleDTO.getId()).orElse(null);
Put in { }

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/services/impl/UserServiceImpl.java
> +        //User existingUser = userRepository.getReferenceById(userToSave.getId());
Remove this line

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/services/impl/UserServiceImpl.java
>      @Transactional
So you need transactions for read methods?

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/test/java/com/samsolutions/employeesdep/controllers/rest/UserControllerIntegrationTest.java
> +        testUsers.clear();
Add empty line

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/test/java/com/samsolutions/employeesdep/repository/UserRepositoryTest.java
> +        /*for (Long id : listIDs) {
Remove this block

2023-03-01 07:52 UTC, AlecKotovichSAM commented on src/test/java/com/samsolutions/employeesdep/repository/UserRepositoryTest.java
> +        //Predicate predicate = User.login.Not(adminLogin);
Remove this line, commented code should not go into main branch

2023-03-23 07:49 UTC, MalishkaMyu commented
I fixed evething

2023-03-24 13:08 UTC, AlecKotovichSAM approved these changes

2023-03-24 13:08 UTC, merged