Entities hibernate
MalishkaMyu/EmployeesDepartment pull request #4
Opened 2022-10-11 06:47 UTC by MalishkaMyu

2022-10-13 06:04 UTC, AlecKotovichSAM requested changes

2022-10-13 06:04 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/entities/Department.java
> +    private long id;
Better use Long instead. Otherwise there will be a problem with nulls

2022-10-13 06:04 UTC, AlecKotovichSAM commented on src/main/java/com/samsolutions/employeesdep/model/entities/Employee.java
> +    private long id;
long -> Long

2022-10-13 06:04 UTC, AlecKotovichSAM commented on src/main/resources/dbscripts/V1.3__change_id_employee_roles.sql
> +ALTER TABLE IF EXISTS public."employee_roles"
Rename employee_roles -> employees_roles

2022-10-17 08:45 UTC, AlecKotovichSAM requested changes
Conversations

2022-10-17 08:59 UTC, MalishkaMyu commented
I've commited changes, not pushed. Is it enough?

2022-10-17 10:20 UTC, AlecKotovichSAM approved these changes

2022-10-17 10:22 UTC, AlecKotovichSAM approved these changes

2022-10-17 10:22 UTC, merged